### PR TITLE
Declare dependency on curses library

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by skogsbaer** [comment]
Thanks!

**Comment by shlevy** [comment]
Thanks! Would you mind pinging this message when there's a new release on hackage?

**Comment by kenranunderscore** [comment]
@shlevy Uhm, this might be a bit late, but: ping :laughing:
Note that I've replaced `curses` with `ncurses` in the meantime. In the unlikely event that this is still relevant to you at all: would that cause any problems for you?

**Comment by shlevy** [comment]
😆 I'm not even sure what I was using this for, thanks for the update though!

**Pull request merged**
